apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: smartlandlord-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding
  namespace: smartlandlord-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: smartlandlord-dev-role
subjects:
- kind: ServiceAccount
  name: smartlandlord-operator-controller-manager
  namespace: smartlandlord-operator-system
