apiVersion: realtortools.realtordevelopments.io/v1alpha1
kind: Smartlandlord
metadata:
  labels:
    app.kubernetes.io/name: smartlandlord-operator
    app.kubernetes.io/managed-by: kustomize
  name: smartlandlord-sample
spec:
  # TODO(user): Add fields here
